// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.27.5
// source: interop.proto

//go:build protoopaque

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParameterType int32

const (
	ParameterType_UNKNOWN ParameterType = 0
	ParameterType_STRING  ParameterType = 1
	ParameterType_INT     ParameterType = 2
	ParameterType_FLOAT   ParameterType = 3
	ParameterType_BOOLEAN ParameterType = 4
)

// Enum value maps for ParameterType.
var (
	ParameterType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STRING",
		2: "INT",
		3: "FLOAT",
		4: "BOOLEAN",
	}
	ParameterType_value = map[string]int32{
		"UNKNOWN": 0,
		"STRING":  1,
		"INT":     2,
		"FLOAT":   3,
		"BOOLEAN": 4,
	}
)

func (x ParameterType) Enum() *ParameterType {
	p := new(ParameterType)
	*p = x
	return p
}

func (x ParameterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParameterType) Descriptor() protoreflect.EnumDescriptor {
	return file_interop_proto_enumTypes[0].Descriptor()
}

func (ParameterType) Type() protoreflect.EnumType {
	return &file_interop_proto_enumTypes[0]
}

func (x ParameterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ProfilerParameter struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	xxx_hidden_Type        ParameterType          `protobuf:"varint,3,opt,name=type,proto3,enum=ParameterType" json:"type,omitempty"`
	xxx_hidden_Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	xxx_hidden_Value       string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfilerParameter) Reset() {
	*x = ProfilerParameter{}
	mi := &file_interop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerParameter) ProtoMessage() {}

func (x *ProfilerParameter) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfilerParameter) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *ProfilerParameter) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ProfilerParameter) GetType() ParameterType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ParameterType_UNKNOWN
}

func (x *ProfilerParameter) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *ProfilerParameter) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *ProfilerParameter) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *ProfilerParameter) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ProfilerParameter) SetType(v ParameterType) {
	x.xxx_hidden_Type = v
}

func (x *ProfilerParameter) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *ProfilerParameter) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type ProfilerParameter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key         string
	Name        string
	Type        ParameterType
	Description string
	Value       string
}

func (b0 ProfilerParameter_builder) Build() *ProfilerParameter {
	m0 := &ProfilerParameter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Value = b.Value
	return m0
}

type ProfilerInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	xxx_hidden_Parameters  *[]*ProfilerParameter  `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfilerInfo) Reset() {
	*x = ProfilerInfo{}
	mi := &file_interop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerInfo) ProtoMessage() {}

func (x *ProfilerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfilerInfo) GetUuid() string {
	if x != nil {
		return x.xxx_hidden_Uuid
	}
	return ""
}

func (x *ProfilerInfo) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ProfilerInfo) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *ProfilerInfo) GetParameters() []*ProfilerParameter {
	if x != nil {
		if x.xxx_hidden_Parameters != nil {
			return *x.xxx_hidden_Parameters
		}
	}
	return nil
}

func (x *ProfilerInfo) SetUuid(v string) {
	x.xxx_hidden_Uuid = v
}

func (x *ProfilerInfo) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ProfilerInfo) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *ProfilerInfo) SetParameters(v []*ProfilerParameter) {
	x.xxx_hidden_Parameters = &v
}

type ProfilerInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid        string
	Name        string
	Description string
	Parameters  []*ProfilerParameter
}

func (b0 ProfilerInfo_builder) Build() *ProfilerInfo {
	m0 := &ProfilerInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Uuid = b.Uuid
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Parameters = &b.Parameters
	return m0
}

type ProfilersInfo struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Profilers *[]*ProfilerInfo       `protobuf:"bytes,1,rep,name=profilers,proto3" json:"profilers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProfilersInfo) Reset() {
	*x = ProfilersInfo{}
	mi := &file_interop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilersInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilersInfo) ProtoMessage() {}

func (x *ProfilersInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfilersInfo) GetProfilers() []*ProfilerInfo {
	if x != nil {
		if x.xxx_hidden_Profilers != nil {
			return *x.xxx_hidden_Profilers
		}
	}
	return nil
}

func (x *ProfilersInfo) SetProfilers(v []*ProfilerInfo) {
	x.xxx_hidden_Profilers = &v
}

type ProfilersInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Profilers []*ProfilerInfo
}

func (b0 ProfilersInfo_builder) Build() *ProfilersInfo {
	m0 := &ProfilersInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Profilers = &b.Profilers
	return m0
}

type SessionInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	xxx_hidden_ProcessName string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	xxx_hidden_Timestamp   string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	xxx_hidden_Profiler    *ProfilerInfo          `protobuf:"bytes,4,opt,name=profiler,proto3" json:"profiler,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_interop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionInfo) GetUuid() string {
	if x != nil {
		return x.xxx_hidden_Uuid
	}
	return ""
}

func (x *SessionInfo) GetProcessName() string {
	if x != nil {
		return x.xxx_hidden_ProcessName
	}
	return ""
}

func (x *SessionInfo) GetTimestamp() string {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return ""
}

func (x *SessionInfo) GetProfiler() *ProfilerInfo {
	if x != nil {
		return x.xxx_hidden_Profiler
	}
	return nil
}

func (x *SessionInfo) SetUuid(v string) {
	x.xxx_hidden_Uuid = v
}

func (x *SessionInfo) SetProcessName(v string) {
	x.xxx_hidden_ProcessName = v
}

func (x *SessionInfo) SetTimestamp(v string) {
	x.xxx_hidden_Timestamp = v
}

func (x *SessionInfo) SetProfiler(v *ProfilerInfo) {
	x.xxx_hidden_Profiler = v
}

func (x *SessionInfo) HasProfiler() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Profiler != nil
}

func (x *SessionInfo) ClearProfiler() {
	x.xxx_hidden_Profiler = nil
}

type SessionInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid        string
	ProcessName string
	Timestamp   string
	Profiler    *ProfilerInfo
}

func (b0 SessionInfo_builder) Build() *SessionInfo {
	m0 := &SessionInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Uuid = b.Uuid
	x.xxx_hidden_ProcessName = b.ProcessName
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Profiler = b.Profiler
	return m0
}

var File_interop_proto protoreflect.FileDescriptor

var file_interop_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x95, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x72, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x72, 0x2a, 0x49, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54,
	0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x04, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_interop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_interop_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_interop_proto_goTypes = []any{
	(ParameterType)(0),        // 0: ParameterType
	(*ProfilerParameter)(nil), // 1: ProfilerParameter
	(*ProfilerInfo)(nil),      // 2: ProfilerInfo
	(*ProfilersInfo)(nil),     // 3: ProfilersInfo
	(*SessionInfo)(nil),       // 4: SessionInfo
}
var file_interop_proto_depIdxs = []int32{
	0, // 0: ProfilerParameter.type:type_name -> ParameterType
	1, // 1: ProfilerInfo.parameters:type_name -> ProfilerParameter
	2, // 2: ProfilersInfo.profilers:type_name -> ProfilerInfo
	2, // 3: SessionInfo.profiler:type_name -> ProfilerInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_interop_proto_init() }
func file_interop_proto_init() {
	if File_interop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interop_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interop_proto_goTypes,
		DependencyIndexes: file_interop_proto_depIdxs,
		EnumInfos:         file_interop_proto_enumTypes,
		MessageInfos:      file_interop_proto_msgTypes,
	}.Build()
	File_interop_proto = out.File
	file_interop_proto_rawDesc = nil
	file_interop_proto_goTypes = nil
	file_interop_proto_depIdxs = nil
}
